
# Data Preparation 1

    In this section of code we will define and prepare our variables, import the raw data, and format each variable
    accordingly. Also, we will define which variables need to be removed if any. In the following section we will 
    describe the final dataset we arrive at.

Freddie Mac has made available loan-level credit performance data on a portion of fully amortizing fixed-rate mortgages that the company purchased or guaranteed from 1999 to 2016. We are using the data for Loan-level origination, monthly loan performance, and actual loss data on a portion of the fully amortizing 30-year fixed-rate Single Family mortgages that Freddie Mac acquired with origination dates from 1999 to the Origination Cutoff Date.The Dataset is a “living” dataset, and as such may periodically be corrected or updated over time.


We will know if we have mined useful knowledge if we will have a statistically significant way of predicting the outcome variable EverDelinquent. We will take alpha = 0.05 to determine a statistically significant result.

In [1]:
# Import pandas as numpy and read in the LoanExport Dataset.
import pandas as pd
import numpy as np

# Read in CSV
df = pd.read_csv('LoanExport.csv', low_memory=False)

# Sometimes Python has errors reading the first column in CSV's so we renamed CreditScore to 'CS'
col_name =df.columns[0]
df=df.rename(columns = {col_name:'CS'})
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 291451 entries, 0 to 291450
Data columns (total 28 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CS                  291451 non-null  int64  
 1   FirstPaymentDate    291451 non-null  int64  
 2   FirstTimeHomebuyer  291451 non-null  object 
 3   MaturityDate        291451 non-null  int64  
 4   MSA                 291451 non-null  object 
 5   MIP                 291451 non-null  int64  
 6   Units               291451 non-null  int64  
 7   Occupancy           291451 non-null  object 
 8   OCLTV               291451 non-null  int64  
 9   DTI                 291451 non-null  int64  
 10  OrigUPB             291451 non-null  int64  
 11  LTV                 291451 non-null  int64  
 12  OrigInterestRate    291451 non-null  float64
 13  Channel             291451 non-null  object 
 14  PPM                 291451 non-null  object 
 15  ProductType         291451 non-nul

(291451, 28)

In [2]:
# Remove attributes that just are not useful
for col in ['FirstPaymentDate','MaturityDate','MSA',
            'Occupancy','Channel','ProductType','LoanSeqNum',
            'SellerName','PostalCode','ServicerName',
            'PropertyState','PPM','PropertyType','LoanPurpose',
            'NumBorrowers']:
    if col in df:
        del df[col]
# Removing NA's
df.dropna(inplace=True)
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
Int64Index: 291451 entries, 0 to 291450
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   CS                  291451 non-null  int64  
 1   FirstTimeHomebuyer  291451 non-null  object 
 2   MIP                 291451 non-null  int64  
 3   Units               291451 non-null  int64  
 4   OCLTV               291451 non-null  int64  
 5   DTI                 291451 non-null  int64  
 6   OrigUPB             291451 non-null  int64  
 7   LTV                 291451 non-null  int64  
 8   OrigInterestRate    291451 non-null  float64
 9   OrigLoanTerm        291451 non-null  int64  
 10  EverDelinquent      291451 non-null  int64  
 11  MonthsDelinquent    291451 non-null  int64  
 12  MonthsInRepayment   291451 non-null  int64  
dtypes: float64(1), int64(11), object(1)
memory usage: 31.1+ MB


(291451, 13)

In [3]:
# Investigate the unique values in the column
df.CS.unique()

array([  0, 335, 342, 363, 366, 370, 375, 391, 396, 445, 462, 466, 471,
       476, 477, 478, 479, 481, 482, 483, 485, 486, 487, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530,
       531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543,
       544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556,
       557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569,
       570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582,
       583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595,
       596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608,
       609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621,
       622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634,
       635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 64

In [3]:
# CS contains a 0 which the data definition states is actually 850.
# Let's convert all 0's to 850
df['CS'] = np.where(df['CS'] == 0, 850, df['CS'])
df.CS.unique()

array([850, 335, 342, 363, 366, 370, 375, 391, 396, 445, 462, 466, 471,
       476, 477, 478, 479, 481, 482, 483, 485, 486, 487, 489, 490, 491,
       492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504,
       505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517,
       518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530,
       531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543,
       544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556,
       557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569,
       570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582,
       583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595,
       596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608,
       609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621,
       622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634,
       635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 64

In [5]:
# Find the values in FirstTimeHomebuyer column
df.FirstTimeHomebuyer.unique()

array(['N', 'X', 'Y'], dtype=object)

In [6]:
# FirstTimeHomebuyer contains X's which stand for unknowns, i.e. Nulls. 
# Need to remove all rows that do not have a valid answer, Y/N, as they are not useful to our research.
df = df[df.FirstTimeHomebuyer != 'X']
df.FirstTimeHomebuyer.unique()

array(['N', 'Y'], dtype=object)

In [7]:
# Check the row and column count of our dataset to see how many rows were just removed.
df.shape

(213436, 13)

In [8]:
# Count values in FirstTimeHomebuyer
df['FirstTimeHomebuyer'].value_counts()

N    184154
Y     29282
Name: FirstTimeHomebuyer, dtype: int64

In [9]:
# Rename FirstTimeHomebuyer to IsFirstTime
df = df.rename(columns = {'FirstTimeHomebuyer':'IsFirstTime'})
# Convert Y/N to 1 or 0 and then count values again to ensure they match
df['IsFirstTime'] = np.where(df['IsFirstTime'] == 'Y', 1, 0)
df['IsFirstTime'].value_counts()

0    184154
1     29282
Name: IsFirstTime, dtype: int64

In [10]:
# Find the values in MIP column
df.MIP.unique()

array([25,  0, 30, 12, 35, 29, 17, 18, 20, 22,  6, 14, 33, 16, 52, 36, 28,
       11, 45, 27, 10, 50, 47,  7, 24, 15, 37, 32, 26,  1, 13, 21, 23, 55,
        4], dtype=int64)

In [11]:
# Find the values in Units column
df.Units.unique()
print('Dataframe shape:', df.shape)
df['Units'].value_counts()

Dataframe shape: (213436, 13)


1    209501
2      3242
3       346
4       345
0         2
Name: Units, dtype: int64

In [12]:
# Units = 0 means that we do not have data on this so it is really a Null value, removing those rows.
df = df[df.Units != 0]
print('Dataframe shape:', df.shape)
df['Units'].value_counts()

Dataframe shape: (213434, 13)


1    209501
2      3242
3       346
4       345
Name: Units, dtype: int64

In [13]:
# Find values in OCLTV
df.OCLTV.unique()
# The OCLTV values check out here.

array([ 89,  73,  75,  76,  78,  90,  95,  80,  77,  85,  93,  70,  74,
        79,  72,  62,  44,  32,  64,  91,  53,  69,  60,  54,  52,  84,
        68,  36,  55,  96,  97,  46,  58,  63,  83,  87,  94,  48,  50,
        51,  67,  86,  81,  66,  71,  82,  88,  26,  59,  57,  61,  30,
        24,  34,  37,  42,  65,  31, 100,   7,  38,  39,  16,  41,  33,
        92,  40,  35,  56,  22,  28,  43,  47,  49,  98,  29,  45,  25,
       103,  10,  18,  23,  20,  15, 102, 101,  14,  21,  27, 105,  19,
         8,   0, 104,  17, 110,  99,  12,   6,  13,   9,  11], dtype=int64)

In [14]:
# Find values in DTI
df.DTI.unique()
# The DTI values check out here.

array([27, 17, 16, 14, 18, 40, 21, 38, 19, 23, 45, 28, 29, 15, 43, 25, 24,
       26, 20, 35, 46, 39, 33, 48, 30, 31, 22, 56, 32, 12,  6, 37, 36, 42,
       34, 11, 41,  8, 44, 55,  0, 51, 10,  7, 47,  9, 13, 65, 54,  2, 53,
       57,  5,  3,  4, 50, 59, 49, 52, 64, 60, 58,  1, 61, 62, 63], dtype=int64)

In [15]:
# Find values in OrigUPB
df.OrigUPB.unique()
# The OrigUPB values check out here.

array([117000, 109000,  88000, 160000, 207000, 111000,  55000,  35000,
       126000, 200000,  70000,  93000,  79000,  54000,  80000, 231000,
       145000, 187000, 148000,  90000,  65000,  86000, 122000, 157000,
        94000,  63000,  50000, 100000, 191000, 204000, 222000, 189000,
        57000, 202000, 137000,  56000, 140000,  18000,  76000,  77000,
       151000, 118000, 182000,  98000,  89000, 172000,  82000, 240000,
       102000, 173000,  51000, 169000, 101000, 152000, 141000,  47000,
       128000, 133000, 135000, 115000, 144000, 146000, 212000, 176000,
       214000, 190000, 227000,  99000,  83000,  49000,  29000, 124000,
       132000, 150000, 300000,  95000, 149000, 162000, 226000, 110000,
       112000, 219000, 236000,  67000, 195000, 164000, 198000,  60000,
       194000, 147000, 104000,  72000, 183000, 154000, 179000,  66000,
       210000,  46000,  96000, 225000, 156000,  45000, 235000, 113000,
       139000,  74000,  68000,  69000, 238000, 142000,  73000,  48000,
      

In [16]:
# Find values in LTV
df.LTV.unique()
# The LTV values check out here.

array([ 89,  73,  75,  76,  78,  90,  95,  80,  77,  85,  93,  70,  74,
        79,  72,  62,  44,  32,  64,  91,  53,  69,  60,  54,  52,  84,
        68,  36,  55,  96,  97,  46,  58,  63,  83,  87,  94,  48,  50,
        51,  67,  86,  81,  66,  71,  82,  88,  26,  59,  57,  61,  30,
        24,  34,  37,  42,  65,  31,   7,  38,  39,  16,  41,  33,  92,
        40,  35,  56,  22,  28,  43,  47, 100,  49,  98,  29,  45,  25,
        10,  18,  23,  20,  15, 103,  14,  21,  27,  19,   8,   0,  17,
        12,   6,  13,   9,  11], dtype=int64)

In [17]:
# Find values in OrigInterestRate
df.OrigInterestRate.unique()
# The values check out here since we see that pandas imported this column as a float type.

array([  6.75 ,   6.5  ,   6.875,   7.125,   7.   ,   7.25 ,   6.625,
         7.75 ,   7.2  ,   7.5  ,   7.625,   7.875,   6.25 ,   8.125,
         7.15 ,   7.375,   6.375,   8.75 ,   7.1  ,   7.05 ,   6.95 ,
         8.   ,   8.625,   8.375,   8.5  ,   6.125,   6.   ,   5.875,
         8.25 ,   8.99 ,   5.625,   9.   ,   5.125,   5.25 ,   9.125,
         6.99 ,   5.375,   8.365,   8.875,   6.975,   7.3  ,   7.313,
         9.625,   9.25 ,   5.75 ,   7.85 ,   8.695,   4.875,   7.775,
         7.29 ,   7.405,   9.5  ,   9.375,   9.75 ,   7.13 ,   5.99 ,
         6.999,   7.055,   7.09 ,   6.785,   7.08 ,   7.025,   7.7  ,
         7.58 ,  10.5  ,   7.55 ,   7.445,   9.875,   6.85 ,   6.925,
         6.9  ,   8.37 ,   7.095,   7.19 ,   7.456,   7.675,   9.675,
         7.475,   7.22 ,   7.17 ,   8.7  ,   7.301,   8.9  ,  10.   ,
         5.5  ,   6.62 ,   7.325,  10.375,   7.8  ,   7.4  ,  10.85 ,
         7.185,   7.245,  11.5  ,   6.94 ,   6.87 ,   7.65 ,   7.312,
         7.28 ,   7.

In [18]:
# Find values in OrigLoanTerm
df.OrigLoanTerm.unique()
# The OrigLoanTerm values check out here.

array([360, 345, 306, 335, 322, 327, 358, 355, 356, 354, 346, 344, 348,
       313, 316, 353, 319, 332, 336, 338, 312, 328, 351, 333, 359, 331,
       337, 334, 357, 330, 350, 341, 343, 325, 326, 324, 347, 352, 329,
       339, 309, 317, 349, 342, 304, 310, 340, 301, 305, 315, 323, 321,
       320, 302, 314, 318, 308, 303, 307, 361, 311], dtype=int64)

In [19]:
# Find values in EverDelinquent
df.EverDelinquent.unique()
# The EverDelinquent values check out here.

array([0, 1], dtype=int64)

In [20]:
# Find values in MonthsInRepayment
df.MonthsInRepayment.unique()
# The MonthsInRepayment values check out here.

array([ 52, 144,  67,  35,  54,  42,  44,  64, 212,  37,  47,  53,  55,
        66,  26,  38,  36,  39,  40,  11, 176,  46, 197, 210,  56, 118,
        63,  24,  28,  91,  50,  22, 211, 199,  23,  30, 125,  41,  76,
        49,  18,  19,  43,  60,  83,  95,  29,  45,  13,   6,  48,  62,
        14,  15, 111,  51,  17,  75,  58,  27,  10,  31, 133, 165, 156,
        33,  68, 205,  57, 159,  81, 191, 194, 114,  59, 100, 134, 128,
        71,   7,  65,  74,  79, 174, 195, 151,  34, 149,  21,  12, 137,
       130,  69,  70, 173, 166,  61, 160,  20, 178,   3,  72, 147,   2,
        32, 164, 139, 108, 148,  92, 209, 102,  87,  94,  73, 123,  16,
       142,   1, 172, 109, 141, 175, 103, 168,   5, 155, 177, 158, 138,
        25, 110,  98,  84, 136,   8, 121, 179,   4, 154, 161, 157, 150,
        80, 170,  77,   9, 183,  93, 143, 162, 126,  89, 208, 184,  82,
       145, 117, 101, 122, 107, 193,  85,  78, 169, 104, 131, 140, 163,
       112, 206, 135, 132, 124, 186, 127, 189, 190, 198, 192, 16

In [21]:
# Create new variable for Credit Range since that is commonly what is looked at in the industry.
# New values = Poor (0-650), Fair (650-700), Good (700-750), Excellent (750-900)
df['CreditRange'] = pd.cut(df.CS,[550,650,700,750,1e6],4,labels=[1,2,3,4])
df.CreditRange.unique()

[4.0, NaN, 1.0, 2.0, 3.0]
Categories (4, int64): [1 < 2 < 3 < 4]

In [22]:
df['CreditRange'].value_counts()

3    72678
4    57183
2    54763
1    28284
Name: CreditRange, dtype: int64

In [23]:
# Create new variable for LTV Range
df['LTV_range'] = pd.cut(df.LTV,[0,25,50,1000],3,labels=['Low','Medium','High'])
df.LTV_range.unique()

[High, Medium, Low, NaN]
Categories (3, object): [High < Low < Medium]

In [24]:
# We get a NaN null return as a possible value
# Checking to ensure this is accurate
print('Is there a Null value in LTV?', df['LTV_range'].isnull().values.any())
print('Dataframe shape:', df.shape)
df['LTV_range'].value_counts()

Is there a Null value in LTV? True
Dataframe shape: (213434, 15)


High      198868
Medium     13202
Low         1361
Name: LTV_range, dtype: int64

In [25]:
# We need to find where these 3 Nan values are.
inds = pd.isnull(df).any(1).nonzero()[0]
pd.isnull(df).any(1).nonzero()[0]

array([   985,    986,    987,    988,    989,    990,    991,    992,
          993,    994,    995,    996,    997,    998,    999,   1000,
         1001,   1002,   1003,   1004,   1005,   1006,   1007,   1008,
         1009,   1010,   1011,   1012,   1013,   1014,   1015,   1016,
         1017,   1018,   1019,   1020,   1021,   1022,   1023,   1024,
         1025,   1026,   1027,   1028,   1029,   1030,   1031,   1032,
         1033,   1034,   1035,   1036,   1037,   1038,   1039,   1040,
         1041,   1042,   1043,   1044,   1045,   1046,   1047,   1048,
         1049,   1050,   1051,   1052,   1053,   1054,   1055,   1056,
         1057,   1058,   1059,   1060,   1061,   1062,   1063,   1064,
         1065,   1066,   1067,   1068,   1069,   1070,   1071,   1072,
         1073,   1074,   1075,   1076,   1077,   1078,   1079,   1080,
         1081,   1082,   1083,   1084,   1085,   1086,   1087,   1088,
         1089,   1090,   1091,   1092,   1093,   1094,   1095,   1096,
      

In [26]:
# Drop the specific rows with Nan for LTV_range as this will be an issue later on.
# I was unable to find a different way to get rid of these Nan's.
indexes_to_keep = set(range(df.shape[0])) - set(inds)
df = df.take(list(indexes_to_keep))
print('Is there a Null value in LTV?', df['LTV_range'].isnull().values.any())
print('Dataframe shape:', df.shape)
df['LTV_range'].value_counts()

Is there a Null value in LTV? False
Dataframe shape: (212905, 15)


High      198358
Medium     13186
Low         1361
Name: LTV_range, dtype: int64

In [27]:
# Create new variable Repay range
df['Repay_range'] = pd.cut(df.MonthsInRepayment,[0,48,96,144,192,240],5,
                           labels=['0-4yrs','4-8yrs','8-12yrs', '12-16yrs', '16-20yrs'])
print('Dataframe shape:', df.shape)
print('Repay_range values:', df.Repay_range.unique())
df['Repay_range'].value_counts()

Dataframe shape: (212905, 16)
Repay_range values: [4-8yrs, 8-12yrs, 0-4yrs, 16-20yrs, 12-16yrs]
Categories (5, object): [0-4yrs < 12-16yrs < 16-20yrs < 4-8yrs < 8-12yrs]


0-4yrs      108653
4-8yrs       73488
8-12yrs      13885
12-16yrs      8728
16-20yrs      8151
Name: Repay_range, dtype: int64

In [28]:
# Final check of our dataframe before moving on.
print('Dataframe shape:', df.shape)
print('Are there any null values in our dataframe (T/F)?', df.isnull().values.any())
df.info()

Dataframe shape: (212905, 16)
Are there any null values in our dataframe (T/F)? False
<class 'pandas.core.frame.DataFrame'>
Int64Index: 212905 entries, 0 to 291450
Data columns (total 16 columns):
CS                   212905 non-null int64
IsFirstTime          212905 non-null int32
MIP                  212905 non-null int64
Units                212905 non-null int64
OCLTV                212905 non-null int64
DTI                  212905 non-null int64
OrigUPB              212905 non-null int64
LTV                  212905 non-null int64
OrigInterestRate     212905 non-null float64
OrigLoanTerm         212905 non-null int64
EverDelinquent       212905 non-null int64
MonthsDelinquent     212905 non-null int64
MonthsInRepayment    212905 non-null int64
CreditRange          212905 non-null category
LTV_range            212905 non-null category
Repay_range          212905 non-null category
dtypes: category(3), float64(1), int32(1), int64(11)
memory usage: 22.5 MB


In [29]:
# Now that we have created the variables we want to investigate further let's group our dataframe by these ranges.
df_grouped = df.groupby(by=['CreditRange'])
df_grouped = df.groupby(by=['CreditRange','LTV_range'])
df_grouped = df.groupby(by=['Repay_range'])
df_grouped = df.groupby(by=['CreditRange','IsFirstTime','LTV_range','Repay_range'])
df_grouped.describe()

CS                         \
                                                 count        mean        std   
CreditRange IsFirstTime LTV_range Repay_range                                   
1           0           High      0-4yrs       11450.0  626.529956  19.843510   
                                  12-16yrs       909.0  625.511551  19.916542   
                                  16-20yrs      1177.0  625.493628  20.070331   
                                  4-8yrs        8280.0  627.101691  19.639019   
                                  8-12yrs       1279.0  626.274433  20.232272   
                        Low       0-4yrs          17.0  627.529412  19.824599   
                                  12-16yrs         2.0  608.000000  35.355339   
                                  16-20yrs         1.0  631.000000        NaN   
                                  4-8yrs          13.0  635.384615  13.859644   
                                  8-12yrs          3.0  637.333333   7.094599   
                        Medium    0-4yrs         286.0  624.125874  20.164018   
                                  12-16yrs        39.0  624.128205  24.192408   
                                  16-20yrs        47.0  619.085106  26.227955   
                                  4-8yrs         210.0  626.152381  19.763085   
                                  8-12yrs         50.0  624.380000  23.455464   
            1           High      0-4yrs        2253.0  625.074567  20.676969   
                                  12-16yrs       187.0  625.336898  19.827722   
                                  16-20yrs       222.0  624.815315  18.847738   
                                  4-8yrs        1599.0  625.818637  19.879100   
                                  8-12yrs        227.0  624.312775  19.971306   
                        Low       8-12yrs          1.0  596.000000        NaN   
                        Medium    0-4yrs           7.0  631.571429  12.488090   
                                  12-16yrs         3.0  629.333333   6.027714   
                                  16-20yrs         4.0  616.500000  16.842407   
                                  4-8yrs          16.0  621.125000  15.239751   
                                  8-12yrs          1.0  639.000000        NaN   
2           0           High      0-4yrs       22976.0  677.335306  14.428621   
                                  12-16yrs      1649.0  677.235294  14.628795   
                                  16-20yrs      1939.0  675.659103  14.436539   
                                  4-8yrs       15655.0  676.947684  14.440027   
...                                                ...         ...        ...   
4           0           High      0-4yrs       21770.0  771.096785  16.729990   
                                  12-16yrs      2025.0  775.115556  17.963305   
                                  16-20yrs      1402.0  774.682596  18.945351   
                                  4-8yrs       14609.0  771.910398  16.944185   
                                  8-12yrs       3469.0  773.554338  16.923832   
                        Low       0-4yrs         334.0  777.943114  17.064259   
                                  12-16yrs        73.0  782.082192  14.416188   
                                  16-20yrs        49.0  783.040816  19.201735   
                                  4-8yrs         235.0  777.893617  15.562438   
                                  8-12yrs        105.0  779.438095  15.772373   
                        Medium    0-4yrs        2871.0  775.854406  16.458555   
                                  12-16yrs       448.0  779.410714  16.650401   
                                  16-20yrs       307.0  777.895765  17.064532   
                                  4-8yrs        2285.0  775.845077  16.568163   
                                  8-12yrs        704.0  777.308239  16.119050   
            1           High      0-4yrs        3064.0  771.980418  20.469600   
  

In [30]:
df_imputed = df_grouped.A(lambda grp: grp.fillna(grp.median()))
df_imputed[['IsFirstTime','EverDelinquent']] = df[['IsFirstTime','EverDelinquent']]
df.dropna(inplace=True)

In [31]:
# Slicing the CreditScore
df_imputed['CreditRange'] = pd.cut(df_imputed.CS,[550,650,700,750,1e6],4,labels=[1,2,3,4]) # this creates a new variable
df_imputed.CreditRange.describe()

count     212905
unique         4
top            3
freq       72678
Name: CreditRange, dtype: int64

In [32]:
# Slicing the LTV
df_imputed['LTV_range'] = pd.cut(df_imputed.LTV,[0,25,50,110],3,labels=['low','medium','high']) # this creates a new variable
df_imputed.LTV_range.describe()

count     212905
unique         3
top         high
freq      198358
Name: LTV_range, dtype: object

In [33]:
# Taking slices of the MonthsInRepayment
df_imputed['Repay_range'] = pd.cut(df_imputed.MonthsInRepayment,[0,48,96,144,192,240],5,labels=['0-4yrs','4-8yrs','8-12yrs', '12-16yrs', '16-20yrs'])
df_imputed.Repay_range.describe()

count     212905
unique         5
top       0-4yrs
freq      108653
Name: Repay_range, dtype: object

In [34]:
df_imputed.head()
df_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 212905 entries, 0 to 291450
Data columns (total 16 columns):
CS                   212905 non-null int64
MIP                  212905 non-null int64
Units                212905 non-null int64
OCLTV                212905 non-null int64
DTI                  212905 non-null int64
OrigUPB              212905 non-null int64
LTV                  212905 non-null int64
OrigInterestRate     212905 non-null float64
OrigLoanTerm         212905 non-null int64
EverDelinquent       212905 non-null int64
MonthsDelinquent     212905 non-null int64
MonthsInRepayment    212905 non-null int64
IsFirstTime          212905 non-null int32
CreditRange          212905 non-null category
LTV_range            212905 non-null category
Repay_range          212905 non-null category
dtypes: category(3), float64(1), int32(1), int64(11)
memory usage: 22.5 MB


This table is a full disclosure of the variables that were provided, removed, or created along with their definitions and values.

| Variables | Modified? | Definition | Values
| :- | :- | :- | :- | :- 
| CreditScore | Yes, renamed to CS | A number summarizing the borrower’s creditworthiness. | 301-850, 0 if 850 
| MIP | No | The % of loss coverage on the loan. | 1-55%, 0 = No MIP
| Units | No | Shows whether the mortgage is a 1,2,3, or 4 unit property. | 1-4 units, X = Unknown
| OCLTV | No | Original Combined Loan-to-Value ratio [Reference LTV for calculation] | 0-200%, X = Unknown
| DTI | No | Original Debt-to-Income ratio. | 0-65%, X = >65 or Unknown
| OrigUPB | No | The unpaid balance of the mortgage on the note date. | Numeric rounded to nearest 1,000
| LTV | No | The Loan to Value ratio [orig mortgage amount / (lesser of appraised value or purchase price)] | 6-105%, X = Unknown
| OrigInterestRate | No | The original note rate as indicated on the mortgage note. | Numeric
| OrigLoanTerm | No | The number of scheduled monthly payments based on the FirstPaymentDate and MaturityDate. | Integer
| EverDelinquent | No | Has the loan has ever been 30 days or more delinquent? | 0 = No, 1 = Yes
| MonthsInRepayment | No | The number of months that the Loan premium has been paid. | Integer
| CreditRange | Created | Made this from CreditScore (CS). | Bad, Good, Very Good, Excellent
| LTV_range | Created | Made this from LTV. | Low, Medium, High
| Repay_range | Created | Made this from MonthsInRepayment. | 0-4yrs, 4-8yrs, 8-12yrs, 12-16yrs, 16-20yrs
| IsFirstTime | Created | Is the purchaser a First Time Homebuyer? | Y or N
| FirstTimeHomebuyer | Removed | Not necessary as we created IsFirstTime variable from this one. |
| MonthsDelinquent | Removed | Not necessary, highly correlated to EverDelinquent |
| FirstPaymentDate | Removed | Not necessary. |
| MaturityDate | Removed | Not necessary. |
| MSA | Removed | Not necessary. |
| Occupancy | Removed | Not necessary. |
| Channel | Removed | Not necessary. |
| PPM | Removed | Not necessary. |
| ProductType | Removed | Not necessary. |
| PropertyState | Removed | Not necessary. |
| PropertyType | Removed | Not necessary. |
| NumBorrowers | Removed | Not necessary. |
| SellerName | Removed | Not necessary. |
| ServicerName | Removed | Not necessary. |

The following table describes the variables that we were provided, will create, and will remove. 


| Provided Variables | Removed Variables | Created Variables
| :- | :- | :- 
|Credit Score | FirstPaymentDate | CreditRange
|FirstPaymentDate | MaturityDate | LTV_range
|FirstTimeHomebuyer | MSA | Repay_range
|MaturityDate | Occupancy | IsFirstTime
|MSA | Channel |
|MIP | PPM |
|Units | ProductType |
|Occupancy | PropertyState |
|OCLTV | PropertyType |
|DTI | NumBorrowers |
|OrigUPB | SellerName |
|LTV | ServicerName |
|OrigInterestRate | FirstTimeHomebuyer |
|Channel |  |
|PPM |  |
|ProductType |  |
|PropertyState |  |
|PropertyType |  |
|OrigLoanTerm |  |
|NumBorrowers |  |
|SellerName |  |
|ServicerName |  |
|EverDelinquent |  |
|MonthsDelinquent |  |
|MonthsInRepayment |  |